spring:
  redis:
    #jedis:
    #  pool:
    #最大连接数量
    #    max-active: 20
    #最大空闲数量
    #    max-active: 20
    #最大等待时间
    #    max-wait: 3000ms
    #最小空闲数量
    #    min-idle: 0
    lettuce:
      pool:
        max-active: 2
        max-idle: 1
        max-wait: 30000ms
        min-idle: 0
      #host: 127.0.0.1
      #port: 6379
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26380,127.0.0.1:26381,127.0.0.1:26382
    password: test1234